# Generated by Django 5.0.1 on 2024-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_alter_utilisateur_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
