# Generated by Django 5.0.1 on 2024-01-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_alter_evenement_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
