# Generated by Django 5.0.1 on 2024-02-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0008_alter_utilisateur_id_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
